#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u "FKDA_X/FKDA_X.py"

# The previous version of this file was commented-out and follows below:
# 
# python -u "FKDA_CX/FKDA_CX.py"
# 
# # The previous version of this file was commented-out and follows below:
# # 
# # python -u "FKDA_C/FKDA_C.py"
# # 
# 
